import std/[algorithm, os, strutils]

import zippy

type
  AssetsGenError* = object of CatchableError

  AssetEntry = object
    path: string
    contentType: string
    etag: string
    staticRel: string

proc assetsGenError(message: string): ref AssetsGenError =
  newException(AssetsGenError, message)

proc nimStringLiteral(value: string): string =
  "\"" & value.replace("\\", "\\\\").replace("\"", "\\\"") & "\""

proc nimImportPath(path: string): string =
  path.replace("\\", "/")

proc generateSingleFileAssets*(distIndex, outPath: string) =
  ## Generate the `viewy_assets` module consumed by `-d:viewyGeneratedAssets`.
  if not fileExists(distIndex):
    raise assetsGenError("frontend build did not produce " & distIndex)

  createDir(parentDir(outPath))
  let rel = relativePath(distIndex, parentDir(outPath)).nimImportPath
  writeFile(outPath,
    "## Generated by viewy build. Do not edit.\n" &
    "const viewyEmbeddedHtml* = staticRead(" & nimStringLiteral(rel) & ")\n")

proc contentType(path: string): string =
  case splitFile(path).ext.toLowerAscii
  of ".html": "text/html; charset=utf-8"
  of ".js", ".mjs": "text/javascript; charset=utf-8"
  of ".css": "text/css; charset=utf-8"
  of ".json": "application/json; charset=utf-8"
  of ".svg": "image/svg+xml"
  of ".png": "image/png"
  of ".jpg", ".jpeg": "image/jpeg"
  of ".gif": "image/gif"
  of ".webp": "image/webp"
  of ".ico": "image/x-icon"
  of ".wasm": "application/wasm"
  of ".txt": "text/plain; charset=utf-8"
  else: "application/octet-stream"

proc generatedGzipName(index: int; path: string): string =
  let ext = splitFile(path).ext
  "asset_" & $index & ext & ".gz"

proc fnv1a(value: string): uint64 =
  result = 14695981039346656037'u64
  for ch in value:
    result = result xor uint64(ord(ch))
    result = result * 1099511628211'u64

proc etagFor(path, content: string): string =
  "\"viewy-" & toHex(fnv1a(path & "\0" & content)) & "\""

proc generateMultiFileAssets(distDir, outPath: string; includeScheme: bool) =
  let distIndex = distDir / "index.html"
  if not fileExists(distIndex):
    raise assetsGenError("frontend build did not produce " & distIndex)

  createDir(parentDir(outPath))
  let gzipDir = parentDir(outPath) / "viewy_assets_served"
  if dirExists(gzipDir):
    removeDir(gzipDir)
  createDir(gzipDir)

  var entries: seq[AssetEntry]
  var files: seq[string]
  for file in walkDirRec(distDir):
    if not fileExists(file):
      continue
    files.add file
  files.sort()

  for index, file in files:
    let rel = relativePath(file, distDir).nimImportPath
    let servedPath = "/" & rel
    let gzipPath = gzipDir / generatedGzipName(index, rel)
    let content = readFile(file)
    writeFile(gzipPath, compress(content))
    let staticRel = relativePath(gzipPath, parentDir(outPath)).nimImportPath
    entries.add AssetEntry(
      path: servedPath,
      contentType: contentType(file),
      etag: etagFor(servedPath, content),
      staticRel: staticRel,
    )

  entries.sort(proc(a, b: AssetEntry): int = cmp(a.path, b.path))
  var servedEntries: seq[string]
  for entry in entries:
    servedEntries.add "  (path: " & nimStringLiteral(entry.path) &
      ", contentType: " & nimStringLiteral(entry.contentType) &
      ", gzipBytes: staticRead(" & nimStringLiteral(entry.staticRel) & ")),"
  var output = "## Generated by viewy build. Do not edit.\n" &
    "const viewyServedDocumentPath* = " & nimStringLiteral("/index.html") & "\n" &
    "const viewyServedAssets* = [\n" &
    servedEntries.join("\n") & "\n" &
    "]\n"
  if includeScheme:
    var schemeEntries: seq[string]
    for entry in entries:
      schemeEntries.add "  (path: " & nimStringLiteral(entry.path) &
        ", mimeType: " & nimStringLiteral(entry.contentType) &
        ", etag: " & nimStringLiteral(entry.etag) &
        ", gzipBytes: staticRead(" & nimStringLiteral(entry.staticRel) & ")),"
    output.add "const viewySchemeDocumentPath* = " &
      nimStringLiteral("/index.html") & "\n" &
      "const viewySchemeAssets* = [\n" &
      schemeEntries.join("\n") & "\n" &
      "]\n"
  writeFile(outPath, output)

proc generateServedAssets*(distDir, outPath: string) =
  ## Generate the `viewy_assets` module consumed by `-d:viewyGeneratedServedAssets`.
  generateMultiFileAssets(distDir, outPath, includeScheme = false)

proc generateSchemeAssets*(distDir, outPath: string) =
  ## Generate the `viewy_assets` module consumed by `-d:viewyGeneratedSchemeAssets`.
  ##
  ## The module keeps the served-mode table for the lite fallback and also emits
  ## scheme-specific path/MIME/ETag/gzip entries for native scheme handlers.
  generateMultiFileAssets(distDir, outPath, includeScheme = true)
