import std/[algorithm, os, strutils]

import zippy
import zippy/crc

type
  AssetsGenError* = object of CatchableError

  AssetEntry = object
    path: string
    contentType: string
    etag: string
    staticRel: string
    contentHash: uint64

proc assetsGenError(message: string): ref AssetsGenError =
  newException(AssetsGenError, message)

proc nimStringLiteral(value: string): string =
  "\"" & value.replace("\\", "\\\\").replace("\"", "\\\"") & "\""

proc nimImportPath(path: string): string =
  path.replace("\\", "/")

proc generateSingleFileAssets*(distIndex, outPath: string) =
  ## Generate the `viewy_assets` module consumed by `-d:viewyGeneratedAssets`.
  if not fileExists(distIndex):
    raise assetsGenError("frontend build did not produce " & distIndex)

  createDir(parentDir(outPath))
  let rel = relativePath(distIndex, parentDir(outPath)).nimImportPath
  writeFile(outPath,
    "## Generated by viewy build. Do not edit.\n" &
    "const viewyEmbeddedHtml* = staticRead(" & nimStringLiteral(rel) & ")\n")

proc contentType(path: string): string =
  case splitFile(path).ext.toLowerAscii
  of ".html": "text/html; charset=utf-8"
  of ".js", ".mjs": "text/javascript; charset=utf-8"
  of ".css": "text/css; charset=utf-8"
  of ".json": "application/json; charset=utf-8"
  of ".svg": "image/svg+xml"
  of ".png": "image/png"
  of ".jpg", ".jpeg": "image/jpeg"
  of ".gif": "image/gif"
  of ".webp": "image/webp"
  of ".ico": "image/x-icon"
  of ".wasm": "application/wasm"
  of ".txt": "text/plain; charset=utf-8"
  else: "application/octet-stream"

proc generatedGzipName(index: int; path: string): string =
  let ext = splitFile(path).ext
  "asset_" & $index & ext & ".gz"

const
  fnvOffset = 14695981039346656037'u64
  fnvPrime = 1099511628211'u64

proc updateFnv1a(hash: var uint64; value: string) =
  for ch in value:
    hash = hash xor uint64(ord(ch))
    hash = hash * fnvPrime

proc fnv1a(value: string): uint64 =
  result = fnvOffset
  result.updateFnv1a(value)

proc etagForBuild(entries: openArray[AssetEntry]): string =
  var hash = fnvOffset
  for entry in entries:
    hash.updateFnv1a(entry.path)
    hash.updateFnv1a("\0")
    hash.updateFnv1a(toHex(entry.contentHash))
    hash.updateFnv1a("\0")
  "\"viewy-" & toHex(hash) & "\""

proc addUint32Le(output: var string; value: uint32) =
  output.add(((value shr 0) and 255).char)
  output.add(((value shr 8) and 255).char)
  output.add(((value shr 16) and 255).char)
  output.add(((value shr 24) and 255).char)

proc gzipDeterministic(content: string): string =
  ## zippy's dfGzip writer intentionally randomizes the filename header.
  ## Emit a minimal, stable gzip wrapper around deterministic deflate bytes.
  result = "\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff"
  result.add compress(content, dataFormat = dfDeflate)
  result.addUint32Le(crc32(content))
  result.addUint32Le(uint32(content.len))

proc generateMultiFileAssets(distDir, outPath: string; includeScheme: bool) =
  let distIndex = distDir / "index.html"
  if not fileExists(distIndex):
    raise assetsGenError("frontend build did not produce " & distIndex)

  createDir(parentDir(outPath))
  let gzipDir = parentDir(outPath) / "viewy_assets_served"
  if dirExists(gzipDir):
    removeDir(gzipDir)
  createDir(gzipDir)

  var entries: seq[AssetEntry]
  var files: seq[string]
  for file in walkDirRec(distDir):
    if not fileExists(file):
      continue
    files.add file
  files.sort()

  for index, file in files:
    let rel = relativePath(file, distDir).nimImportPath
    let servedPath = "/" & rel
    let gzipPath = gzipDir / generatedGzipName(index, rel)
    let content = readFile(file)
    writeFile(gzipPath, gzipDeterministic(content))
    let staticRel = relativePath(gzipPath, parentDir(outPath)).nimImportPath
    entries.add AssetEntry(
      path: servedPath,
      contentType: contentType(file),
      staticRel: staticRel,
      contentHash: fnv1a(content),
    )

  entries.sort(proc(a, b: AssetEntry): int = cmp(a.path, b.path))
  let buildEtag = etagForBuild(entries)
  for entry in entries.mitems:
    entry.etag = buildEtag
  var servedEntries: seq[string]
  for entry in entries:
    servedEntries.add "  (path: " & nimStringLiteral(entry.path) &
      ", contentType: " & nimStringLiteral(entry.contentType) &
      ", gzipBytes: staticRead(" & nimStringLiteral(entry.staticRel) & ")),"
  var output = "## Generated by viewy build. Do not edit.\n" &
    "const viewyServedDocumentPath* = " & nimStringLiteral("/index.html") & "\n" &
    "const viewyServedAssets* = [\n" &
    servedEntries.join("\n") & "\n" &
    "]\n"
  if includeScheme:
    var schemeEntries: seq[string]
    for entry in entries:
      schemeEntries.add "  (path: " & nimStringLiteral(entry.path) &
        ", mimeType: " & nimStringLiteral(entry.contentType) &
        ", etag: " & nimStringLiteral(entry.etag) &
        ", gzipBytes: staticRead(" & nimStringLiteral(entry.staticRel) & ")),"
    output.add "const viewySchemeDocumentPath* = " &
      nimStringLiteral("/index.html") & "\n" &
      "const viewySchemeAssets* = [\n" &
      schemeEntries.join("\n") & "\n" &
      "]\n"
  writeFile(outPath, output)

proc generateServedAssets*(distDir, outPath: string) =
  ## Generate the `viewy_assets` module consumed by `-d:viewyGeneratedServedAssets`.
  generateMultiFileAssets(distDir, outPath, includeScheme = false)

proc generateSchemeAssets*(distDir, outPath: string) =
  ## Generate the `viewy_assets` module consumed by `-d:viewyGeneratedSchemeAssets`.
  ##
  ## The module keeps the served-mode table for the lite fallback and also emits
  ## scheme-specific path/MIME/ETag/gzip entries for native scheme handlers.
  generateMultiFileAssets(distDir, outPath, includeScheme = true)
