import std/[algorithm, os, strutils]

import zippy

type
  AssetsGenError* = object of CatchableError

proc assetsGenError(message: string): ref AssetsGenError =
  newException(AssetsGenError, message)

proc nimStringLiteral(value: string): string =
  "\"" & value.replace("\\", "\\\\").replace("\"", "\\\"") & "\""

proc nimImportPath(path: string): string =
  path.replace("\\", "/")

proc generateSingleFileAssets*(distIndex, outPath: string) =
  ## Generate the `viewy_assets` module consumed by `-d:viewyGeneratedAssets`.
  if not fileExists(distIndex):
    raise assetsGenError("frontend build did not produce " & distIndex)

  createDir(parentDir(outPath))
  let rel = relativePath(distIndex, parentDir(outPath)).nimImportPath
  writeFile(outPath,
    "## Generated by viewy build. Do not edit.\n" &
    "const viewyEmbeddedHtml* = staticRead(" & nimStringLiteral(rel) & ")\n")

proc contentType(path: string): string =
  case splitFile(path).ext.toLowerAscii
  of ".html": "text/html; charset=utf-8"
  of ".js", ".mjs": "text/javascript; charset=utf-8"
  of ".css": "text/css; charset=utf-8"
  of ".json": "application/json; charset=utf-8"
  of ".svg": "image/svg+xml"
  of ".png": "image/png"
  of ".jpg", ".jpeg": "image/jpeg"
  of ".gif": "image/gif"
  of ".webp": "image/webp"
  of ".ico": "image/x-icon"
  of ".wasm": "application/wasm"
  of ".txt": "text/plain; charset=utf-8"
  else: "application/octet-stream"

proc generatedGzipName(index: int; path: string): string =
  let ext = splitFile(path).ext
  "asset_" & $index & ext & ".gz"

proc generateServedAssets*(distDir, outPath: string) =
  ## Generate the `viewy_assets` module consumed by `-d:viewyGeneratedServedAssets`.
  let distIndex = distDir / "index.html"
  if not fileExists(distIndex):
    raise assetsGenError("frontend build did not produce " & distIndex)

  createDir(parentDir(outPath))
  let gzipDir = parentDir(outPath) / "viewy_assets_served"
  if dirExists(gzipDir):
    removeDir(gzipDir)
  createDir(gzipDir)

  var entries: seq[string]
  var files: seq[string]
  for file in walkDirRec(distDir):
    if not fileExists(file):
      continue
    files.add file
  files.sort()

  for index, file in files:
    let rel = relativePath(file, distDir).nimImportPath
    let servedPath = "/" & rel
    let gzipPath = gzipDir / generatedGzipName(index, rel)
    writeFile(gzipPath, compress(readFile(file)))
    let staticRel = relativePath(gzipPath, parentDir(outPath)).nimImportPath
    entries.add "  (path: " & nimStringLiteral(servedPath) &
      ", contentType: " & nimStringLiteral(contentType(file)) &
      ", gzipBytes: staticRead(" & nimStringLiteral(staticRel) & ")),"

  entries.sort()
  writeFile(outPath,
    "## Generated by viewy build. Do not edit.\n" &
    "const viewyServedDocumentPath* = " & nimStringLiteral("/index.html") & "\n" &
    "const viewyServedAssets* = [\n" &
    entries.join("\n") & "\n" &
    "]\n")
